# -*- coding: utf-8 -*-
"""Image_enhancement_algorithm_combining_histogram_equalization_and _bilateral_filtering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nTlh7rglwI4plA4wOejfknYRjCfSOmaw
"""

!pip install opencv-python scikit-image pywavelets matplotlib pandas

import cv2
import numpy as np
import matplotlib.pyplot as plt
import pywt
import pandas as pd
import os
import zipfile

from skimage.metrics import structural_similarity as ssim

"""**Upload (Image OR Zip Folder)**"""

from google.colab import files
uploaded = files.upload()

file_name = list(uploaded.keys())[0]

if file_name.endswith(".zip"):
    with zipfile.ZipFile(file_name, 'r') as zip_ref:
        zip_ref.extractall("dataset")
    img_dir = "dataset"
else:
    os.makedirs("dataset", exist_ok=True)
    os.rename(file_name, f"dataset/{file_name}")
    img_dir = "dataset"

print("Dataset path:", img_dir)

"""**Load Images**"""

image_files = []

for root, dirs, files in os.walk(img_dir):
    for f in files:
        if f.lower().endswith((".png",".jpg",".jpeg")):
            image_files.append(os.path.join(root,f))

print("Total images:", len(image_files))

"""**METRICS FUNCTION**"""

def compute_metrics(ref, img):

    ref = ref.astype(np.float32)
    img = img.astype(np.float32)

    mse = np.mean((ref - img) ** 2)

    if mse == 0:
        p = 100
    else:
        p = 10 * np.log10((255**2)/mse)

    s = ssim(ref, img, channel_axis=2, data_range=255)

    gray = cv2.cvtColor(img.astype(np.uint8), cv2.COLOR_BGR2GRAY)
    hist = cv2.calcHist([gray],[0],None,[256],[0,256])
    prob = hist / np.sum(hist)
    prob = prob[prob > 0]
    entropy = -np.sum(prob * np.log2(prob))

    contrast = np.std(img)

    return p, s, entropy, contrast

"""**BASIC METHODS**"""

def apply_HE(img):
    yuv = cv2.cvtColor(img, cv2.COLOR_BGR2YUV)
    yuv[:,:,0] = cv2.equalizeHist(yuv[:,:,0])
    return cv2.cvtColor(yuv, cv2.COLOR_YUV2BGR)

def apply_CLAHE(img):
    lab = cv2.cvtColor(img, cv2.COLOR_BGR2LAB)
    l, a, b = cv2.split(lab)
    clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8,8))
    l = clahe.apply(l)
    return cv2.cvtColor(cv2.merge((l,a,b)), cv2.COLOR_LAB2BGR)

def apply_RD(img):
    yuv = cv2.cvtColor(img, cv2.COLOR_BGR2YUV)
    Y, U, V = cv2.split(yuv)

    Y = Y.astype(np.float32) / 255.0
    blur = cv2.GaussianBlur(Y, (15,15), 0)

    rd = np.log(Y + 1e-6) - np.log(blur + 1e-6)
    rd = cv2.normalize(rd, None, 0, 255, cv2.NORM_MINMAX).astype(np.uint8)

    yuv = cv2.merge([rd, U, V])
    return cv2.cvtColor(yuv, cv2.COLOR_YUV2BGR)

def apply_ESIHE(img):
    yuv = cv2.cvtColor(img, cv2.COLOR_BGR2YUV)
    y = yuv[:, :, 0]

    mean = int(np.mean(y))

    lower_mask = y <= mean
    upper_mask = y > mean

    lower = y.copy()
    upper = y.copy()

    lower[~lower_mask] = 0
    upper[~upper_mask] = 0

    lower_eq = cv2.equalizeHist(lower)
    upper_eq = cv2.equalizeHist(upper)

    result = np.zeros_like(y)
    result[lower_mask] = lower_eq[lower_mask]
    result[upper_mask] = upper_eq[upper_mask]

    yuv[:, :, 0] = result
    return cv2.cvtColor(yuv, cv2.COLOR_YUV2BGR)

def apply_RGHS(img):
    # Convert to LAB (use BGR if image from cv2.imread)
    lab = cv2.cvtColor(img, cv2.COLOR_BGR2LAB)
    L, A, B = cv2.split(lab)

    # Percentile-based stretching (robust RGHS-like)
    p_low, p_high = np.percentile(L, (1, 99))

    # Avoid division by zero
    if p_high - p_low < 1e-6:
        L_stretch = L.copy()
    else:
        L_stretch = (L - p_low) * 255.0 / (p_high - p_low)
        L_stretch = np.clip(L_stretch, 0, 255)

    # Optional blending (prevents over-enhancement)
    L_final = cv2.addWeighted(L, 0.5, L_stretch.astype(np.uint8), 0.5, 0)

    lab = cv2.merge([L_final.astype(np.uint8), A, B])
    return cv2.cvtColor(lab, cv2.COLOR_LAB2BGR)

"""**OUR METHOD**"""

def our_method(img):

    img_f = img.astype(np.float32) / 255.0
    output = np.zeros_like(img_f)

    for c in range(3):

        channel = img_f[:, :, c]

        # -------- WAVELET --------
        LL, (LH, HL, HH) = pywt.dwt2(channel, 'haar')

        # -------- LOW FREQUENCY --------
        LL = cv2.bilateralFilter(LL.astype(np.float32), d=5, sigmaColor=50, sigmaSpace=50)
        LL = np.maximum(LL, 1e-6)

        # Retinex
        log_LL = np.log1p(LL)
        blur = cv2.GaussianBlur(LL, (3,3), 0.5)
        LL_retinex = log_LL - 0.7 * np.log1p(blur + 1e-6)

        # -------- HE (instead of CLAHE) --------
        LL_norm = cv2.normalize(LL_retinex, None, 0, 255, cv2.NORM_MINMAX).astype(np.uint8)

        LL_he = cv2.equalizeHist(LL_norm)

        # Blend (important)
        LL_he = cv2.addWeighted(LL_norm, 0.6, LL_he, 0.4, 0)
        LL_he = LL_he.astype(np.float32) / 255.0

        # -------- HIGH FREQUENCY --------
        def threshold(x):
            T = 0.2 * np.std(x)
            return np.where(np.abs(x) > T, x, 0)

        LH = threshold(LH)
        HL = threshold(HL)
        HH = threshold(HH)

        # -------- RECONSTRUCTION --------
        rec = pywt.idwt2((LL_he, (LH, HL, HH)), 'haar')
        rec = cv2.resize(rec, (img.shape[1], img.shape[0]))

        output[:, :, c] = rec

    # -------- FINAL --------
    output = np.clip(output, 0, 1)

    # Gamma boost
    output = np.power(output, 0.85)

    final = (output * 255).astype(np.uint8)

    # Sharpening
    kernel = np.array([[0,-1,0],
                       [-1,6,-1],
                       [0,-1,0]])

    final = cv2.filter2D(final, -1, kernel)

    return final

"""**STAGE-TRACKING VERSION**"""

def our_method_with_stages(img):

    stages = {}

    img_f = img.astype(np.float32) / 255.0
    stages["Input"] = img.copy()

    output = np.zeros_like(img_f)

    for c in range(3):

        channel = img_f[:, :, c]

        # -------- WAVELET --------
        LL, (LH, HL, HH) = pywt.dwt2(channel, 'haar')

        # Save LL (resize + 3-channel)
        LL_vis = cv2.normalize(LL, None, 0, 255, cv2.NORM_MINMAX).astype(np.uint8)
        LL_vis = cv2.resize(LL_vis, (img.shape[1], img.shape[0]))
        LL_vis = cv2.cvtColor(LL_vis, cv2.COLOR_GRAY2RGB)
        stages["Wavelet_LL"] = LL_vis

        # -------- LOW FREQUENCY --------
        LL = cv2.bilateralFilter(LL.astype(np.float32), 5, 50, 50)
        LL = np.maximum(LL, 1e-6)

        blur = cv2.GaussianBlur(LL, (3,3), 0.5)
        LL_retinex = np.log1p(LL) - 0.7 * np.log1p(blur + 1e-6)

        LL_norm = cv2.normalize(LL_retinex, None, 0, 255, cv2.NORM_MINMAX).astype(np.uint8)
        LL_he = cv2.equalizeHist(LL_norm)

        LL_he = cv2.addWeighted(LL_norm, 0.6, LL_he, 0.4, 0)

        # Save enhanced LL
        LL_he_vis = cv2.resize(LL_he, (img.shape[1], img.shape[0]))
        LL_he_vis = cv2.cvtColor(LL_he_vis, cv2.COLOR_GRAY2RGB)
        stages["LL_Enhanced"] = LL_he_vis

        LL_he = LL_he.astype(np.float32) / 255.0

        # -------- HIGH FREQUENCY --------
        def threshold(x):
            T = 0.2 * np.std(x)
            return np.where(np.abs(x) > T, x, 0)

        LH = threshold(LH)
        HL = threshold(HL)
        HH = threshold(HH)

        # -------- RECONSTRUCTION --------
        rec = pywt.idwt2((LL_he, (LH, HL, HH)), 'haar')
        rec = cv2.resize(rec, (img.shape[1], img.shape[0]))

        output[:, :, c] = rec

    output = np.clip(output, 0, 1)

    rec_img = (output * 255).astype(np.uint8)
    stages["Reconstructed"] = rec_img

    output = np.power(output, 0.85)

    final = (output * 255).astype(np.uint8)

    kernel = np.array([[0,-1,0],
                       [-1,6,-1],
                       [0,-1,0]])

    final = cv2.filter2D(final, -1, kernel)

    stages["Final"] = final

    return final, stages

"""**PROCESS ALL IMAGES**"""

os.makedirs("outputs", exist_ok=True)

results = []
stage_results = []

def ensure_rgb(img):
    if len(img.shape) == 2:
        return cv2.cvtColor(img, cv2.COLOR_GRAY2RGB)
    return img


def fix_shape(img, ref):
    if img.shape != ref.shape:
        img = cv2.resize(img, (ref.shape[1], ref.shape[0]))
    if len(img.shape) == 2:
        img = cv2.cvtColor(img, cv2.COLOR_GRAY2RGB)
    return img


for path in image_files:

    img = cv2.imread(path)
    if img is None:
        continue

    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    name = os.path.basename(path)

    # -------- METHODS --------
    methods = {
        "Original": img,
        "HE": apply_HE(img),
        "CLAHE": apply_CLAHE(img),
        "RD": apply_RD(img),
        "ESIHE": apply_ESIHE(img),
        "RGHS": apply_RGHS(img),
        "HE+Bilateral": cv2.bilateralFilter(apply_HE(img), 5, 75, 75),
        "Our": our_method(img)
    }

    for m, out in methods.items():

        out = ensure_rgb(out)

        try:
            p, s, e, c = compute_metrics(img, out)
        except:
            continue

        results.append({
            "Image": name,
            "Method": m,
            "PSNR": p,
            "SSIM": s,
            "Entropy": e,
            "Contrast": c
        })

    # -------- STAGE TRACKING --------
    final, stage_dict = our_method_with_stages(img)

    for stage_name, stage_img in stage_dict.items():

        stage_img = fix_shape(stage_img, img)

        try:
            p, s, e, c = compute_metrics(img, stage_img)
        except:
            continue

        stage_results.append({
            "Image": name,
            "Stage": stage_name,
            "PSNR": p,
            "SSIM": s,
            "Entropy": e,
            "Contrast": c
        })

"""**METHOD COMPARISON PRINT**"""

print("\n===== PER IMAGE METHOD METRICS =====\n")

df_methods = pd.DataFrame(results)

for img_name in df_methods["Image"].unique():

    print(f"\n===== Image: {img_name} =====\n")

    temp = df_methods[df_methods["Image"] == img_name].copy()

    order = ["Original","HE","CLAHE","RD","ESIHE","RGHS","HE+Bilateral","Our"]

    temp["Method"] = pd.Categorical(temp["Method"], categories=order, ordered=True)
    temp = temp.sort_values("Method")

    print(temp[["Method","PSNR","SSIM","Entropy","Contrast"]].round(3).to_string(index=False))

    print("\n" + "-"*60)

"""**STAGE-WISE PRINT (FINAL)**"""

print("\n===== STAGE-WISE METRICS =====\n")

df_stage = pd.DataFrame(stage_results)

for img_name in df_stage["Image"].unique():

    print(f"\n===== Image: {img_name} =====\n")

    temp = df_stage[df_stage["Image"] == img_name].copy()

    order = ["Input","Wavelet_LL","LL_Enhanced","Reconstructed","Final"]

    temp["Stage"] = pd.Categorical(temp["Stage"], categories=order, ordered=True)
    temp = temp.sort_values("Stage")

    print(temp[["Stage","PSNR","SSIM","Entropy","Contrast"]].round(3).to_string(index=False))

    print("\n" + "-"*60)

"""**Average comparison table**"""

df = pd.DataFrame(results)

order = ["Original","HE","CLAHE","RD","ESIHE","RGHS","HE+Bilateral","Our"]

# Compute averages
table = df.groupby("Method").mean(numeric_only=True)

# Reorder properly
table = table.reindex(order)

# Handle infinity safely
table = table.replace([np.inf, -np.inf], np.nan)

print("\n===== Comparison of various algorithms (AVERAGE) =====\n")
print(table.round(3))

"""# **Sample Image**"""

# Select ONE image
path = image_files[10]

img = cv2.imread(path)
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

name = os.path.basename(path)

# -------- Fusion (HE + Bilateral) --------
def fusion_method(img):
    return cv2.bilateralFilter(apply_HE(img), 5, 75, 75)

fusion = fusion_method(img)
our = our_method(img)

# -------- METHODS --------
methods = [
    ("Original", img, "black"),
    ("HE", apply_HE(img), "blue"),
    ("CLAHE", apply_CLAHE(img), "green"),
    ("RD", apply_RD(img), "orange"),
    ("ESIHE", apply_ESIHE(img), "purple"),
    ("RGHS", apply_RGHS(img), "brown"),
    ("HE+Bilateral", fusion, "cyan"),
    ("Our Method", our, "red")
]

#  1. IMAGE + HISTOGRAM DISPLAY

rows = len(methods)

plt.figure(figsize=(12, rows * 3))
plt.suptitle(f"Image: {name}", fontsize=16, y=1.02)

for i, (mname, im, color) in enumerate(methods):

    # Image
    plt.subplot(rows, 2, 2*i + 1)
    plt.imshow(im)
    plt.title(mname)
    plt.axis('off')

    # Histogram (grayscale for clarity)
    gray = cv2.cvtColor(im, cv2.COLOR_RGB2GRAY)

    plt.subplot(rows, 2, 2*i + 2)
    plt.hist(gray.ravel(), bins=256, range=(0,256), density=True, color=color)
    plt.axvline(np.mean(gray), color='yellow', linestyle='--')
    plt.grid(alpha=0.3)
    plt.title(f"{mname} Histogram")

plt.tight_layout(rect=[0, 0, 1, 0.97])
plt.show()

# 2. METHOD METRICS (THIS IMAGE)

print("\n===== METHOD METRICS (THIS IMAGE) =====\n")

method_rows = []

for mname, im, _ in methods:

    try:
        p, s, e, c = compute_metrics(img, im)
    except:
        continue

    method_rows.append([mname, p, s, e, c])

df_m = pd.DataFrame(method_rows, columns=["Method","PSNR","SSIM","Entropy","Contrast"])

order = ["Original","HE","CLAHE","RD","ESIHE","RGHS","HE+Bilateral","Our Method"]
df_m["Method"] = pd.Categorical(df_m["Method"], categories=order, ordered=True)
df_m = df_m.sort_values("Method")

print(df_m.round(3).to_string(index=False))

# 3. STAGE-WISE METRICS (OUR METHOD)

print("\n===== STAGE-WISE METRICS (OUR METHOD) =====\n")

final, stage_dict = our_method_with_stages(img)

stage_rows = []

def fix_shape(im, ref):
    if im.shape != ref.shape:
        im = cv2.resize(im, (ref.shape[1], ref.shape[0]))
    if len(im.shape) == 2:
        im = cv2.cvtColor(im, cv2.COLOR_GRAY2RGB)
    return im

for stage_name, stage_img in stage_dict.items():

    stage_img = fix_shape(stage_img, img)

    try:
        p, s, e, c = compute_metrics(img, stage_img)
    except:
        continue

    stage_rows.append([stage_name, p, s, e, c])

df_s = pd.DataFrame(stage_rows, columns=["Stage","PSNR","SSIM","Entropy","Contrast"])

order_stage = ["Input","Wavelet_LL","LL_Enhanced","Reconstructed","Final"]
df_s["Stage"] = pd.Categorical(df_s["Stage"], categories=order_stage, ordered=True)
df_s = df_s.sort_values("Stage")

print(df_s.round(3).to_string(index=False))